# Generated by Django 2.2.6 on 2019-12-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='no_of_item',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
