# Generated by Django 2.2.6 on 2019-12-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191212_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='secondname',
            new_name='second_name',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
