# Generated by Django 2.2.6 on 2020-01-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderlist_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=100000),
        ),
    ]
