# Generated by Django 2.2.6 on 2020-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderlist_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soap',
            name='price',
            field=models.IntegerField(),
        ),
    ]
