# Generated by Django 2.2.6 on 2020-01-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200102_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soap',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100000),
        ),
    ]
