# Generated by Django 2.2.6 on 2020-01-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200102_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soap',
            name='price',
            field=models.IntegerField(),
        ),
    ]
