# Generated by Django 2.2.6 on 2020-01-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderlist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='phone_number',
            field=models.IntegerField(max_length=11),
        ),
    ]
