# Generated by Django 2.2.6 on 2020-01-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200103_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
