# Generated by Django 2.2.6 on 2020-01-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_orderlist_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='uuid',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
